### ISSUE TITLE
Rasbats: version 1.1 seems to bomb when enabled 

### ISSUE THREAD

**Issue by rgleason** [nohal/survey_pi#4]
I've tried a version I compiled and also downloading the release version.
They both seem to bomb Opencpn v4.8.4 when enabled.
I have copied the three files into my opencpn 4.8.4 directory.

**Comment by nohal** [comment]
I have never released any such version, why is this issue here?

**Comment by rgleason** [comment]
Yes, I will close it.

**Comment by rgleason** [comment]
Intended for Rasbats
